from boltiot import Bolt, Sms #Import Sms and Bolt class from boltiot library
import json, time

minimum_limit = 30 # the distance between wall and sensor

API_KEY = 'your bolt cloud api key'
DEVICE_ID = 'your bolt device id'

# Credentials required to send SMS
SSID = 'your twilo ssid' 
AUTH_TOKEN = 'your twilo auth token' 
FROM_NUMBER = 'number generated by twilo'
TO_NUMBER = 'your number with country code'

mybolt = Bolt(API_KEY, DEVICE_ID) #Create object to fetch data
sms = Sms(SSID, AUTH_TOKEN, TO_NUMBER, FROM_NUMBER) #Create object to send SMS
response = mybolt.serialRead('10')
print(response)

while True: 
    print ("Reading sensor value")
    response = mybolt.serialRead('10') 
    data = json.loads(response) 
    print("Sensor value is: " + str(data['value']))
    try: 
        sensor_value = int(data['value']) 
        if  sensor_value < minimum_limit:
            print("Making request to Twilio to send a SMS")
            response = sms.send_sms("An Intuder has breached your home " +str(sensor_value))
            print("Response received from Twilio is: " + str(response))
            print("Status of SMS at Twilio is :" + str(response.status))
    except Exception as e: 
        print ("Error occured: Below are the details")
        print (e)
    time.sleep(10)
